livedst: Add openapi spec for the API
SWxTREC/documentation pull request #5
Opened 2023-11-16 20:59 UTC by greglucas

Adding the openapi spec for the livedst models

2023-11-16 23:35 UTC, jennyknuth requested changes

2023-11-16 23:35 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "description": "The LiveDst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [LiveDst plots](https://swx-t
Let's try to consistently brand it as "Live Dst".

2023-11-16 23:35 UTC, jennyknuth commented on dst/livedst-openapi.json
> +        "operationId": "findPetsByTags",
no pets here!

2023-11-16 23:35 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "description": "The LiveDst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [LiveDst plots](https://swx-t
Maybe "The Live Dst API enables easier public access to the real-time Dst…"

2023-11-16 23:36 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "title": "LiveDst API",
Live Dst API

2023-11-16 23:37 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "description": "The LiveDst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [LiveDst plots](https://swx-t
"Live Dst plots"

2023-11-16 23:39 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "description": "The LiveDst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [LiveDst plots](https://swx-t
And maybe the link for swx-trec.com should say "Related tools and applications" or something. A platform sounds intimidating and technical!

2023-11-17 00:33 UTC, greglucas commented on dst/livedst-openapi.json
> +        "operationId": "findPetsByTags",
Thanks!

2023-11-17 00:33 UTC, greglucas commented on dst/livedst-openapi.json
> +    "description": "The LiveDst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [LiveDst plots](https://swx-t
Made all those changes. I thought it was all one word, so thanks for pointing that out!

2023-11-17 02:14 UTC, jennyknuth approved these changes

2023-11-17 02:16 UTC, jennyknuth commented on dst/livedst-openapi.json
> +    "description": "The Live Dst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [Live Dst plots](https://swx
last tiny thing, do you want the lowercase "live Dst predictions" to be changed to "real time Dst predictions" so as not to be confusing, or do you like it used again as an adjective?

2023-11-17 03:26 UTC, greglucas commented on dst/livedst-openapi.json
> +    "description": "The Live Dst API enables easier public access to the live Dst predictions made\nby CU's space weather machine learning group.\n\nSome useful links:\n- [Live Dst plots](https://swx
Good suggestion. I just made that change too.

2023-11-17 15:25 UTC, merged